spring.application.name=proyecto-integrador

# Servidor
server.port=8080

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:projectsdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Ejecutar data.sql al arrancar
spring.sql.init.mode=always

# Consola H2 (útil en IntelliJ / navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
