spring.application.name=nakano
server.port=8080
spring.datasource.url=jdbc:h2:mem:nakano
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.h2.console.enabled=true
